<!DOCTYPE html>
<html lang="en">
<head>
	<title>HTML FORM</title>
</head>
<body>
    <From action="Task1"method="post">
    <table border="1px">
        <tr>
            <td>Name:</td>
            <td><input type="text" name="" value="" > </td>
        </tr>
        <td>
						
            <input type="submit" name="" value="Submit">
        </td>

</table>

</form>
</body>

